config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'signin', sign_out: 'signout', sign_up: 'signup'},
             :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
    
    resources :posts do
      member do
        patch "like", to: "posts#like"
        patch "unlike", to: "posts#unlike"
      end
      resources :comments, only: [:create, :destroy], shallow: true
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'search/index'
  get 'search', to: 'search#index'

  get 'pages/about'
  get 'pages/contact'
  get 'pages/privacy'
  get 'feed', to: 'pages#feed'

  root "pages#feed"
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
            foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
            foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { maximum: 40 }
  validates :name, presence: true, length: { maximum: 100 }
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id" 
    Post.where("user_id IN (#{following_ids})
                OR user_id = :user_id", user_id: id)
  end

  def liked
    liked_posts_ids = "SELECT votable_id FROM votes
                       WHERE voter_id = :user_id"
    Post.where("id IN (#{liked_posts_ids})", user_id: id)
  end

  def follow(user)
    following << user
  end

  def unfollow(user)
    following.delete(user)
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy]
  after_action :verify_authorized

  def index
    @users = authorize User.order("created_at").page(params[:page]).per(10)
  end

  def show
      @posts = Post.includes(:user).where(user_id: @user.id).limit(5).order("created_at DESC").page(params[:page]).per(4)
      @liked = @user.liked.with_attached_images.limit(5).order("created_at DESC").page(params[:page]).per(4)
  end

  def edit
  end

  def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_path, flash: { success: "User successfully deleted." } }
      end
  end

  def following
    @user = authorize User.find_by(id: params[:id])
    @following = @user.following.order("created_at").page(params[:page]).per(3)
  end

  def followers
    @user = authorize User.find_by(id: params[:id])
    @followers = @user.followers.order("created_at").page(params[:page]).per(3)
  end

  private

  def set_user
    @user = authorize User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(email)
        gravatar_id = Digest::MD5::hexdigest(email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: "Gravatar", class: "gravatar")
      end
end

app/views/users/_follow_form.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary w-100" %>
<% end %>

app/views/users/_info.html.erb
<div class="me-4 mt-2 d-flex flex-column">
	<p class="img-fluid mt-1"><%= gravatar_for user.email %></p>
	<% if policy(user).edit? %>
		<%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark" %>
	<% else %>
		<div id="follow_actions">
			<% if current_user.following?(user) %>
				<%= render 'unfollow_form' %>
			<% else %>
				<%= render 'follow_form' %>
			<% end %>
		</div>
	<% end %>
</div>

<div class="mt-3 ms-4">
	<div class="wrapper align-items-center">
		<h2 class="username"><%= user.name %></h2>
		<% if !user.website.blank? %>
			<%= link_to user.website do %>
					<span class="ms-3"><i class="fa fa-external-link-alt" aria-hidden="true"></i></span>
			<% end %>
		<% end %>
	</div>
	<p class="email"><%= user.email %></p>
	<p><%= user.bio %></p>
	<%= render 'stats', user: @user %>
</div>

app/views/users/_stats.html.erb
<div class="d-flex text-center">
  <div>
    <%= link_to user_posts_path(@user) do %>
      <p class="h6"><%= user.posts.count %><span class="small text-muted ms-1">posts</span></p>
    <% end %>
  </div>
  <div class="ms-5">
    <%= link_to followers_user_path do %>
      <p class="h6"><span id="followers"><%= user.followers.count %></span><span class="small text-muted ms-1">followers</span></p>
    <% end %>
  </div>
  <div class="ms-5">
    <%= link_to following_user_path do %>
      <p class="h6"><span id="following"><%= user.following.count %></span><span class="small text-muted ms-1">following</span></p>
    <% end %>
  </div>
</div>

app/views/users/_tabs.html.erb
<ul class="nav tabs">
  <li class="nav-item">
    <a class="nav-link active" id="pills-posts-tab" href="#" data-bs-toggle="pill" data-bs-target="#pills-posts" role="tab" aria-controls="pills-posts" aria-selected="false">
      POSTS
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-liked-tab" href="#" data-bs-toggle="pill" data-bs-target="#pills-liked" role="tab" aria-controls="pills-tagged" aria-selected="false">
      LIKED
    </a>
  </li>
</ul>
<div class="tab-content py-4 profile-tabs" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-posts" role="tabpanel" aria-labelledby="pills-home-tab">
    <%= turbo_frame_tag "posts_paginate_page" do %>
      <div class="row g-2">
          <% posts.each do |post| %>
              <div class="col-6 mx-auto">
                <%= link_to [user, post], data: { turbo_frame: "_top" } do %>
                  <%= render 'shared/carousel', post: post %>
                <% end %>
              </div>
          <% end %>
          <div class="d-flex justify-content-center mt-5">
            <%= paginate posts, class: "pagination" %>
          </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="pills-liked" role="tabpanel" aria-labelledby="pills-liked-tab">
    <%= turbo_frame_tag "liked_paginate_page" do %>
      <div class="row g-2">
        <% liked.each do |post| %>
            <div class="col-6 mx-auto">
              <%= link_to [user, post], data: { turbo_frame: "_top" } do %>
                <%= render 'shared/carousel', post: post %>
              <% end %>
            </div>
        <% end %>
        <div class="d-flex justify-content-center mt-5">
          <%= paginate liked, class: "pagination" %>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div> 

app/views/users/_unfollow_form.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-secondary w-100" %>
<% end %>

app/views/users/followers.html.erb
<div class="user-profile">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-5">Followers</h1>
      <% @followers.each do |user| %>
        <div class="user my-4">
          <span class="img-fluid mt-1 pe-5"><%= gravatar_for user.email %> <%= link_to user.name, user, class: "mx-3" %></span>
        </div>
        <hr/>
      <% end %>
      <div class="d-flex justify-content-center">
        <%= paginate @followers, class: "pagination" %>
      </div>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="user-profile">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-5">Following</h1>
      <% @following.each do |user| %>
        <div class="user my-4">
          <span class="img-fluid mt-1 pe-5"><%= gravatar_for user.email %> <%= link_to user.name, user, class: "mx-3" %></span>
        </div>
        <hr/>
      <% end %>
      <div class="d-flex justify-content-center">
        <%= paginate @following, class: "pagination" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>

<div class="user-profile">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-5">Users</h1>
      <% @users.each do |user| %>
        <div class="user my-4 d-flex align-items-center justify-content-between">
          <span class="img-fluid mt-1 pe-5"><%= gravatar_for user.email %> <%= link_to "#{user.name}", user, class: "mx-3" %></span>
          <% if policy(user).destroy? %>
            <%= link_to user_path(user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
              <i class="fas fa-times fa-xs" aria-hidden="true" style="color: gray;"></i>
            <% end %>
          <% end %>
        </div>
        <hr/>
      <% end %>
      <div class="d-flex justify-content-center my-5">
        <%= paginate @users, class: "pagination" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<div class="user-profile">
  <div class="row d-flex justify-content-center align-items-center">
    <div class="col col-lg-7 col-lg-6">
        <div class="d-flex justify-content-center">
          <%= render 'info', user: @user %>
        </div>
      </div>
      <div class="pt-5 text-black">
        <%= render 'tabs', user: @user, posts: @posts, liked: @liked %>
      </div>
    </div>
</div>