config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'signin', sign_out: 'signout', sign_up: 'signup'},
             :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
    
    resources :posts do
      member do
        patch "like", to: "posts#like"
        patch "unlike", to: "posts#unlike"
      end
      resources :comments, only: [:create, :destroy], shallow: true
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'search/index'
  get 'search', to: 'search#index'

  get 'pages/about'
  get 'pages/contact'
  get 'pages/privacy'
  get 'feed', to: 'pages#feed'

  root "pages#feed"
end

app/views/shared/_carousel.html.erb
<div id="carousel-post-<%= post.id %>" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% if post.images.attached? %>
      <% post.images.each do |image| %>
        <% if image.variable? %>
          <% if image == post.images.first %>
            <div class="carousel-item active" data-bs-interval="3000">
          <% else %>
            <div class="carousel-item" data-bs-interval="4000">
          <% end %>
           <%= image_tag image.variant(resize_to_limit: [600, 600]), class: 'd-block w-100' %>
          </div>
        <% end %>
      <% end  %>
    <% end %>
    <% if post.images.size > 1 %>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel-post-<%= post.id %>" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel-post-<%= post.id %>" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    <% end %>
  </div>
</div>

app/views/shared/_comment.html.erb
<div class="mb-2 d-flex justify-content-between" id="<%= dom_id comment %>">
	<div>
  	  <span><strong><%= comment.user.username %></strong></span>
	    <span class="text-muted ms-2"><%= comment.content %></span>
	</div>
	<% if policy(comment).destroy? %>
    <%= link_to comment_path(comment), data: { turbo_method: :delete } do %>
        <i class="fas fa-times fa-xs" aria-hidden="true" style="color: gray;"></i>
    <% end %>
	<% end %>
</div>

app/views/shared/_comment_form.html.erb
<%= form_with(model: [user, post, comment]) do |f| %>
  <div class="mb-3">
    <%= f.hidden_field :user_id, value: user.id %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.text_field :content, class: "form-control border-0", placeholder: "Add a comment ...", autocomplete: :off %>
  </div>
<% end %>

app/views/shared/_comments.html.erb
<div id="comments">
    <% post.comments.each do |comment| %>
        <%= render 'shared/comment', comment: comment %>
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <h5>
        <%= I18n.t("errors.messages.not_saved",
                   count: resource.errors.count,
                   resource: resource.class.model_name.human.downcase)
        %>
      </h5>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_like.html.erb
<%= turbo_frame_tag post do %>
  <%= link_to unlike_user_post_path(post.user, post), data: { turbo_method: :patch }, class: "icons" do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
  <% end %>
  <strong><%= render 'shared/likes', post: post %></strong>
<% end %>

app/views/shared/_likes.html.erb
<p><%= pluralize(post.get_likes.size, "like") %></p>

app/views/shared/_post.html.erb
<div class="post mb-5">
  <div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
      <div class="user-avatar">
        <%= gravatar_for post.user.email %>
        <%= link_to user_path(post.user) do %>
          <%= post.user.username %>
        <% end %>
      </div>
      <% if policy(post).destroy? %>
        <%= link_to user_post_path(post.user, post), data: { turbo_method: :delete, turbo_confirm: 'Delete post?' }, class: "icons" do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
      <%= render 'shared/carousel', post: post %>
    <div class="card-body">
      <div class="rows">
        <% if current_user.liked? post %>
          <%= render 'shared/like', post: post %>
        <% else %>
          <%= render 'shared/unlike', post: post %>
        <% end %>
      </div>
      <div class="post-time text-muted mb-2">
        <%= link_to "#{time_ago_in_words(post.created_at).upcase} AGO", [post.user, post] %>
      </div>
      <p class="card-text content">
        <% post.content.to_s.split(' ').each do |word| %>
          <% if word.start_with?('#') %>
            <%= link_to word, search_path(query: word) %>
          <%else %>
            <%= word %>
          <%end %>
        <% end %>
      </p>
      <% if show_comments == true %>
        <div class="row mt-4" id="new_comment">
          <%= render 'shared/comment_form', user: post.user, post: post, comment: Comment.new %>
        </div>
        <%= render partial: 'shared/comments', locals: { post: post } %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_posts.html.erb
<div class="row justify-content-center">
  <div class="col-md-7">
  <% posts.each do |post| %>
    <%= render 'shared/post', post: post, show_comments: false %>
  <% end %>
  <div class="d-flex justify-content-center">
    <%= paginate posts, class: "pagination" %>
  </div>
  </div>
</div>

app/views/shared/_unlike.html.erb
<%= turbo_frame_tag post do %>
  <%= link_to like_user_post_path(post.user, post), data: { turbo_method: :patch }, class: "icons" do %>
    <i class="far fa-heart" aria-hidden="true"></i>
  <% end %>
  <strong><%= render 'shared/likes', post: post %></strong>
<% end %>