config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'signin', sign_out: 'signout', sign_up: 'signup'},
             :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
    
    resources :posts do
      member do
        patch "like", to: "posts#like"
        patch "unlike", to: "posts#unlike"
      end
      resources :comments, only: [:create, :destroy], shallow: true
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'search/index'
  get 'search', to: 'search#index'

  get 'pages/about'
  get 'pages/contact'
  get 'pages/privacy'
  get 'feed', to: 'pages#feed'

  root "pages#feed"
end

app/views/layouts/_footer.html.erb
<footer class="mt-auto bg-light">
  <div class="container">
    <ul class="nav justify-content-center border-bottom py-2 my-2">
      <li class="nav-item">
        <%= link_to "About", pages_about_path, class: "nav-link px-2 text-muted" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", pages_contact_path, class: "nav-link px-2 text-muted" %>
      </li>      
      <li class="nav-item">
        <%= link_to "Privacy", pages_privacy_path, class: "nav-link px-2 text-muted" %>
      </li>  
    </ul>
    <p class="text-center text-muted py-2">&copy; 2022 Photos, Inc</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="logo">
			<%= link_to root_path, class: "navbar-brand", id: "logo", alt: 'Photo', title: 'Photo' do %>
				<i class="bi bi-camera-fill"></i>
				<span>Photos</span>
			<% end %>
    </div>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navBarToggle" aria-controls="navBarToggle" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
    <div class="collapse navbar-collapse" id="navBarToggle">
			<% if user_signed_in? %>
				<div class="ms-auto">
					<%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
						<%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: '#Search' %>
					<% end %>
				</div>
			<% end %>
			<ul class="navbar-nav ms-auto navbar-action-section">
				<% if user_signed_in? %>
					<li>
						<%= link_to new_user_post_path(current_user), alt: 'New Post', title: 'New post' do %>
							<i class="fa fa-plus"></i>
						<% end %>
					</li>
					<li>
						<%= link_to feed_path do %>
							<i class="fa fa-home"></i>
						<% end %>
					</li>
					<li class="dropdown">
						<a href="#" data-toggle="dropdown" role="button" data-bs-toggle="dropdown">
							<i class="fa fa-user"></i>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Users",  users_path, class: "dropdown-item" %></li>
							<li><hr class="dropdown-divider"></li>
							<li><%= link_to "Profile", current_user, alt: 'Profile', title: 'Profile', class: "dropdown-item" %></li>
							<li><hr class="dropdown-divider"></li>
							<li>
								<%= link_to "Sign out", destroy_user_session_path, alt: 'Sign out', title: 'Sign out', data: { turbo_method: :delete }, class: "dropdown-item" %>
							</li>
						</ul>
					</li>
				<% else %>
					<%= link_to new_user_session_path, alt: 'Sign in', title: 'Sign in' do %> 
						<span><i class="fa fa-sign-in-alt" aria-hidden="true"></i></span>
					<% end %>
				<% end %>
			</ul> 
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title("Photos", yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>